---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# DemografixeR

<!-- badges: start -->
<!-- badges: end -->

DemografixeR is an API wrapper of all 3 Demografix API's - all in one:

* [https://genderize.io/](https://genderize.io/)
* [https://agify.io/](https://agify.io/)
* [https://nationalize.io/](https://nationalize.io/)


## Installation

You can install the released version of DemografixeR from [CRAN](https://CRAN.R-project.org) with:

``` r
if (!require("devtools")) install.packages("devtools")
devtools::install_github("matbmeijer/DemografixeR")
```

## Example

This is a basic example which shows you how to estimate **nationality**, **gender** and **age** by a given name:

```{r example}
library(DemografixeR)

df<-data.frame(names=c("Ana", NA, "Pedro",
                       "Francisco", "Maria", "Elena"),
                 country=c(NA, NA, "ES",
                           "DE", "ES", "NL"), stringsAsFactors = FALSE)

df %>% dplyr::mutate(guessed_nationality=nationalize(name = names),
                guessed_gender=genderize(name = names, country_id = country),
                guessed_age=agify(name = names, country_id = country)) %>% 
  knitr::kable()


```
